name = "ComposableCommands"
uuid = "b5b47461-4a42-4db3-bdf2-684fadd57bc3"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "0.2.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
OrderedCollections = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
